/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class Lavadero1 extends javax.swing.JFrame {

    /**
     * Creates new form Lavadero
     */
    public Lavadero1() {
        setTitle("El Veloz");
        this.setMinimumSize(new Dimension(250,150));
        setLocationRelativeTo(null);
        setLocation(600,50);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtdato1 = new javax.swing.JTextField();
        txtdato2 = new javax.swing.JTextField();
        txtdato3 = new javax.swing.JTextField();
        txtdato4 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        Box1 = new javax.swing.JCheckBox();
        Box4 = new javax.swing.JCheckBox();
        Box2 = new javax.swing.JCheckBox();
        Box5 = new javax.swing.JCheckBox();
        Box3 = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        rtexaco = new javax.swing.JRadioButton();
        rpetrobras = new javax.swing.JRadioButton();
        rcoexito = new javax.swing.JRadioButton();
        rshell = new javax.swing.JRadioButton();
        jSeparator4 = new javax.swing.JSeparator();
        rparticular = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        rpublico = new javax.swing.JRadioButton();
        roficial = new javax.swing.JRadioButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        refectivo = new javax.swing.JRadioButton();
        rcheque = new javax.swing.JRadioButton();
        rtarjetas = new javax.swing.JRadioButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtdato5 = new javax.swing.JTextField();
        txtdato6 = new javax.swing.JTextField();
        txtdato7 = new javax.swing.JTextField();
        txtdato8 = new javax.swing.JTextField();
        Boton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtdato9 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtdato10 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtdato11 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel1.setText("Placa");

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel3.setText("Fecha");

        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setText("Celular");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText("LAVADERO DE CARROS EL VELOZ");

        txtdato1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtdato2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdato2ActionPerformed(evt);
            }
        });

        txtdato3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtdato4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Vehiculo");

        jComboBox1.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Automovil", "Campero", "Camioneta", "Camion" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel7.setText("Tipo Vehiculo");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Servicio");

        Box1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        Box1.setText("Lavada General");

        Box4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        Box4.setText("Lavada Motor");
        Box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box4ActionPerformed(evt);
            }
        });

        Box2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        Box2.setText("Lavada por Debajo");
        Box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2ActionPerformed(evt);
            }
        });

        Box5.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        Box5.setText("Grafito");
        Box5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box5ActionPerformed(evt);
            }
        });

        Box3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        Box3.setText("Lavada Tapiceria");
        Box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Cuartos");

        buttonGroup1.add(rtexaco);
        rtexaco.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        rtexaco.setText("Texaco");
        rtexaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtexacoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rpetrobras);
        rpetrobras.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        rpetrobras.setText("Petrobras");
        rpetrobras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpetrobrasActionPerformed(evt);
            }
        });

        buttonGroup1.add(rcoexito);
        rcoexito.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        rcoexito.setText("Coexito");
        rcoexito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcoexitoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rshell);
        rshell.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        rshell.setText("Shell");
        rshell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rshellActionPerformed(evt);
            }
        });

        buttonGroup2.add(rparticular);
        rparticular.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        rparticular.setText("Particular 5%");
        rparticular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rparticularActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Descuentos tipo vehiculo");

        buttonGroup2.add(rpublico);
        rpublico.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        rpublico.setText("Publico 10%");

        buttonGroup2.add(roficial);
        roficial.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        roficial.setText("Oficial 0%");

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Descuentos medio de pago");

        buttonGroup3.add(refectivo);
        refectivo.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        refectivo.setText("Efectivo 10%");
        refectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refectivoActionPerformed(evt);
            }
        });

        buttonGroup3.add(rcheque);
        rcheque.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        rcheque.setText("Cheque 10%");

        buttonGroup3.add(rtarjetas);
        rtarjetas.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        rtarjetas.setText("Tarjetas 0%");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Pago del servicio");

        jLabel13.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel13.setText("Servicio");

        jLabel14.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel14.setText("Descuento por servicio");

        jLabel15.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel15.setText("Descuento por medio de pago");

        jLabel16.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel16.setText("Total");

        txtdato5.setEditable(false);
        txtdato5.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        txtdato5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtdato6.setEditable(false);
        txtdato6.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        txtdato6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtdato7.setEditable(false);
        txtdato7.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        txtdato7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtdato8.setEditable(false);
        txtdato8.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        txtdato8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        Boton1.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        Boton1.setText("Calcular");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });

        txtdato9.setEditable(false);
        txtdato9.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        txtdato9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel18.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel18.setText("Aceite");

        txtdato10.setText("0");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Tipo de Aceite");

        txtdato11.setEditable(false);
        txtdato11.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        txtdato11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel20.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel20.setText("Subtotal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7)
                        .addGap(36, 36, 36)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roficial)
                                    .addComponent(jLabel10)
                                    .addComponent(rpublico)
                                    .addComponent(rparticular))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(refectivo)
                                        .addComponent(jLabel11))
                                    .addComponent(rcheque, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rtarjetas, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(157, 157, 157)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rshell)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rcoexito)
                                                .addGap(107, 107, 107)
                                                .addComponent(txtdato10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(rpetrobras)
                                    .addComponent(rtexaco))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)))))
                .addGap(34, 34, 34))
            .addComponent(jSeparator7)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(txtdato1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtdato2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3)))))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdato3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdato4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(197, 197, 197))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Box1)
                            .addComponent(Box4))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Box5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Box2)
                                .addGap(92, 92, 92)
                                .addComponent(Box3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtdato11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel13))
                                    .addGap(71, 71, 71)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtdato5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtdato7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtdato6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtdato8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtdato9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(71, 71, 71)
                        .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel8)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtdato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdato4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box2)
                    .addComponent(Box3)
                    .addComponent(Box1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box4)
                    .addComponent(Box5))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rtexaco)
                                    .addComponent(rcoexito)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(txtdato10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rpetrobras)
                            .addComponent(rshell))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rparticular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rpublico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(roficial))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(refectivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rcheque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rtarjetas)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtdato5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtdato9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txtdato11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdato6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdato8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdato7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(185, 185, 185))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rparticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rparticularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rparticularActionPerformed

    private void rshellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rshellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rshellActionPerformed

    private void rcoexitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcoexitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcoexitoActionPerformed

    private void rpetrobrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpetrobrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rpetrobrasActionPerformed

    private void rtexacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtexacoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtexacoActionPerformed

    private void Box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box3ActionPerformed

    private void Box5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box5ActionPerformed

    private void Box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box2ActionPerformed

    private void Box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void refectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refectivoActionPerformed

    private void txtdato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdato2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdato2ActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        // TODO add your handling code here:
        String plc, nom, cel, fec;
        int valor=0, valor2=0, subtotal=0, aceite=0, valor3=0, valor4=0, valor5=0, total=0;
        double auto=0, pago=0, total1=0;
        
        //Datos generales
        
        plc= txtdato1.getText();
        nom= txtdato2.getText();
        cel= txtdato3.getText();
        fec= txtdato4.getText();
        
        //Lavado general
        if(jComboBox1.getSelectedItem()=="Automovil" && Box1.isSelected()) valor=12000;
        if(jComboBox1.getSelectedItem()=="Campero" && Box1.isSelected())  valor=14000;
        if(jComboBox1.getSelectedItem()=="Camioneta" && Box1.isSelected())valor=20000;
        if(jComboBox1.getSelectedItem()=="Camion" && Box1.isSelected()) valor=30000;
       
        //Lavado Debajo
         if(jComboBox1.getSelectedItem()=="Automovil" && Box2.isSelected()) valor2=15000;
         if(jComboBox1.getSelectedItem()=="Campero" && Box2.isSelected()) valor2=18000;
         if(jComboBox1.getSelectedItem()=="Camioneta" && Box2.isSelected()) valor2=21000;
         if(jComboBox1.getSelectedItem()=="Camion" && Box2.isSelected())valor2=40000;
   
          //Lavado tapiceria
         if(jComboBox1.getSelectedItem()=="Automovil" && Box3.isSelected()) valor3=45000;
         if(jComboBox1.getSelectedItem()=="Campero" && Box3.isSelected()) valor3=50000;
         if(jComboBox1.getSelectedItem()=="Camioneta" && Box3.isSelected()) valor3=52000;
         if(jComboBox1.getSelectedItem()=="Camion" && Box3.isSelected())valor3=38000;
      
          //Lavado motor
         if(jComboBox1.getSelectedItem()=="Automovil" && Box4.isSelected()) valor4=8000;
         if(jComboBox1.getSelectedItem()=="Campero" && Box4.isSelected()) valor4=10000;
         if(jComboBox1.getSelectedItem()=="Camioneta" && Box4.isSelected()) valor4=12000;
         if(jComboBox1.getSelectedItem()=="Camion" && Box4.isSelected())valor4=14000;
         
          //Grafito
         if(jComboBox1.getSelectedItem()=="Automovil" && Box5.isSelected()) valor5=30000;
         if(jComboBox1.getSelectedItem()=="Campero" && Box5.isSelected()) valor5=35000;
         if(jComboBox1.getSelectedItem()=="Camioneta" && Box5.isSelected()) valor5=38000;
         if(jComboBox1.getSelectedItem()=="Camion" && Box5.isSelected())valor5=40000;
         
        subtotal=valor+valor2+valor3+valor4+valor5;
        txtdato5.setText(String.valueOf(subtotal));
        
        //Aceite
        
        if(rtexaco.isSelected())aceite=25000;
        if(rcoexito.isSelected())aceite=27000;
        if(rpetrobras.isSelected())aceite=26000;
        if(rshell.isSelected())aceite=28000;
        
        txtdato9.setText(String.valueOf(aceite));
        int m;
        m=Integer.parseInt(txtdato10.getText());
        m=m*aceite;
        txtdato9.setText(String.valueOf(m));
        
        //Subtotal
        
        int i,j;
        i=Integer.parseInt(txtdato5.getText());
        j=Integer.parseInt(txtdato9.getText());
        total=i+j;
        txtdato11.setText(String.valueOf(total));
        
        //Descuento tipo de vehiculo
        
        if(rparticular.isSelected())auto=0.05;
        if(rpublico.isSelected())auto=0.10;
        if(roficial.isSelected())auto=0;
        
        txtdato6.setText(String.valueOf(auto));
        double c;
        c=Integer.parseInt(txtdato11.getText());
        c=c*auto;
        txtdato6.setText(String.valueOf(c));
        
        //Descuento medio de pago
        
        if(refectivo.isSelected())pago=0.10;
        if(rcheque.isSelected())pago=0.10;
        if(rtarjetas.isSelected())pago=0;
        
        txtdato8.setText(String.valueOf(pago));
        double n;
        n=Integer.parseInt(txtdato11.getText());
        n=n*pago;
        txtdato8.setText(String.valueOf(n));
        
        //Total 
        
        double l,p,h;
       
        l=Double.parseDouble(txtdato11.getText());
        p=Double.parseDouble(txtdato6.getText());
        h=Double.parseDouble(txtdato8.getText());
        total1=l-p-h;
        txtdato7.setText(String.valueOf(total1));
       
        JOptionPane.showMessageDialog(null, "Placa del Vehiculo: " +plc+"\n"+"Nombre del Cliente: "+nom+"\n"+"Celular del Cliente: "+cel+
                "\n"+"Fecha: "+fec+"\n"+"Total a pagar:"+"$"+total1);
    }//GEN-LAST:event_Boton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lavadero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lavadero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lavadero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lavadero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lavadero1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JCheckBox Box1;
    private javax.swing.JCheckBox Box2;
    private javax.swing.JCheckBox Box3;
    private javax.swing.JCheckBox Box4;
    private javax.swing.JCheckBox Box5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JRadioButton rcheque;
    private javax.swing.JRadioButton rcoexito;
    private javax.swing.JRadioButton refectivo;
    private javax.swing.JRadioButton roficial;
    private javax.swing.JRadioButton rparticular;
    private javax.swing.JRadioButton rpetrobras;
    private javax.swing.JRadioButton rpublico;
    private javax.swing.JRadioButton rshell;
    private javax.swing.JRadioButton rtarjetas;
    private javax.swing.JRadioButton rtexaco;
    private javax.swing.JTextField txtdato1;
    private javax.swing.JTextField txtdato10;
    private javax.swing.JTextField txtdato11;
    private javax.swing.JTextField txtdato2;
    private javax.swing.JTextField txtdato3;
    private javax.swing.JTextField txtdato4;
    private javax.swing.JTextField txtdato5;
    private javax.swing.JTextField txtdato6;
    private javax.swing.JTextField txtdato7;
    private javax.swing.JTextField txtdato8;
    private javax.swing.JTextField txtdato9;
    // End of variables declaration//GEN-END:variables
}
